chucknorris/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ChuckNorrisJokeView.as_view(), name="chuck"), 
]

shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Index.as_view(), name='index'),
    path('superheroes/', include('superheroes.urls')),
    path('chucknorris/', include('chucknorris.urls')),
    path('weather/', include('weather.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

superheroes/urls.py
from django.urls import path
from . import views

# Create your views here.


urlpatterns = [
    path('', views.SuperheroesView.as_view(), name='superheroes'),
    path('<int:pk>/', views.SuperheroDetailView.as_view(), name='superhero_detail'),
    path('create/', views.SuperheroCreateView.as_view(), name='superhero_create'),
    path('<int:pk>/update/', views.SuperheroUpdateView.as_view(), name='superhero_update'),
    path('<int:pk>/delete/', views.SuperheroDeleteView.as_view(), name='superhero_delete'),
]

weather/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.WeatherSearchView.as_view(), name='weather_search'),
    path('result/<str:city>/', views.WeatherResultView.as_view(), name='weather_result'),

]

superheroes/models.py
from django.db import models

# Create your models here.

class Superhero(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nimi')
    civillian_name = models.CharField(max_length=100, verbose_name='Kodanikunimi')
    age = models.IntegerField(verbose_name='Vanus')
    location = models.CharField(max_length=100, verbose_name='Asukoht')
    description = models.TextField(blank=True, null=True, verbose_name="Kirjeldus")
    image = models.ImageField(upload_to='superheroes', blank=True, null=True, verbose_name='Pilt')


    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Superheroes'
        ordering = ['name']

    

weather/models.py
from django.db import models

# Create your models here.

weather/forms.py
from django import forms


class WeatherSearchForm(forms.Form):
    city = forms.CharField(max_length=100, label="Linn", widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Sisesta linna nimi',
    }))

chucknorris/views.py
from django.shortcuts import render
import requests
from django.views.generic.base import TemplateView

# Create your views here.




class ChuckNorrisJokeView(TemplateView):
    template_name = 'chucknorris/chuck_joke.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        response = requests.get("https://api.chucknorris.io/jokes/random")
        if response.status_code == 200:
            data = response.json()
            context['joke'] = data.get('value')
        else:
            context['joke'] = "Oops! Couldn't fetch a Chuck Norris joke right now."
        return context

shop/views.py
from django.views.generic import TemplateView



class Index(TemplateView):
    template_name = 'shop/index.html'

superheroes/views.py
from datetime import datetime
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Superhero


class SuperheroesView(ListView):
    model = Superhero
    template_name = 'superheroes/superheroes.html'
    context_object_name = 'superheroes'


class SuperheroDetailView(DetailView):
    model = Superhero
    template_name = 'superheroes/superhero_detail.html'
    context_object_name = 'hero'

class SuperheroCreateView(CreateView):
    model = Superhero
    fields = '__all__'
    template_name = 'superheroes/superhero_form.html'
    success_url = reverse_lazy('superheroes')
    context_object_name = 'hero'


class SuperheroUpdateView(UpdateView):
    model = Superhero
    fields = '__all__'
    template_name = 'superheroes/superhero_form.html'
    success_url = reverse_lazy('superheroes')
    context_object_name = 'hero'


class SuperheroDeleteView(DeleteView):
    model = Superhero
    template_name = 'superheroes/superhero_delete.html'
    success_url = reverse_lazy('superheroes')
    context_object_name = 'hero'

weather/views.py
from django.shortcuts import render
import requests
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.urls import reverse
from django.http import HttpResponseRedirect
from.forms import WeatherSearchForm

# Create your views here.

API_KEY = "fe4e885cc104b4114c1fa726c63b1f18"



class WeatherSearchView(FormView):
    template_name = 'weather/weather.html'
    form_class = WeatherSearchForm

    def form_valid(self, form):
        city = form.cleaned_data['city']
        return HttpResponseRedirect(reverse('weather_result', kwargs={'city': city}))

    
class WeatherResultView(TemplateView):
    template_name = 'weather/result.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        city = kwargs.get('city')
        url = f'http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric'

        try:
            response = requests.get(url)
            response.raise_for_status()

            data = response.json()
            context['weather'] = {
                'city': data['name'],
                'temperature': data['main']['temp'],
                'feels_like': data['main']['feels_like'],
                'humidity': data['main']['humidity'],
                'wind_speed': data['wind']['speed'],
                'wind_direction': data['wind']['deg'],
                'icon': data['weather'][0]['icon'],
            }
        except requests.exceptions.RequestException as e:
            context['weather'] = {'error': f"Error fetching weather data: {str(e)}"}
        except KeyError:
            context['weather'] = {'error': f"Invalid response from API for city '{city}'."}

        return context

chucknorris/templates/chucknorris/chuck_joke.html
{%extends 'base.html'%}

{% block title %}Chuck Norris{% endblock title %}

{% block body %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card text-center shadow">
                <div class="card-header bg-primary text-white">
                    <h3>Chuck Norrise naljad</h3>
                </div>
                <div class="card-body">
                    <p class="lead" id="joke-text">{{ joke }}</p>
                    <a href="{% url 'chuck' %}" class="btn btn-success mt-3">Järgmine nali</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

shop/templates/shop/index.html
{%extends 'base.html' %}

{% block title %}Pealeht{% endblock title %}


{% block body %}

<div class="min-h-screen bg-gray-900 flex items-center justify-center pb-10">
    <div class="bg-gray-800 p-8 rounded-xl shadow-lg text-center space-y-6">
        

        <h1 class="text-5xl font-extrabold dark:text-white">Klas Korporatsioon</h1>
        <p class="ms-2 font-semibold text-gray-500 dark:text-gray-400">Innovatsioon tulevikuks, kujundades homset.</p>
<p class="text-lg font-normal text-gray-500 lg:text-xl dark:text-gray-400">Klas Korporatsioon on ülemaailmne liider kõrgtehnoloogia, farmaatsia ja bioinseneriteaduse valdkonnas. Oma tipptasemel uurimiskeskuste ja vankumatu pühendumusega arengule muudab Klas Korporatsioon tööstusharusid ja seab uuesti paika võimalikkuse piirid.</p>

        <p class="max-w-2xl text-lg font-medium leading-relaxed text-gray-400 mx-auto">
            Klas Korporatsiooni missioon on parandada inimeste elu läbi murranguliste avastuste, viies maailma helgema ja jätkusuutlikuma tuleviku suunas.
        </p>
        <p class="max-w-2xl text-lg font-medium leading-relaxed text-gray-400 mx-auto pb-">
            Kujundame maailma üks läbimurre korraga.
        </p>
    </div>
</div>


{% endblock body %}

superheroes/templates/superheroes/superhero_delete.html
{%extends 'base.html'%}

{% block title %}Kustuta {{hero.name}}{% endblock title %}

{% block body %}
<div class="container mt-5">
    <div class="card shadow-sm">
        <div class="card-body">
            <h1 class="card-title text-danger">Kinnita Kustutamine</h1>
            <p class="card-text">Olete kindel, et soovite kustutada kangelase <strong>"{{ object.name }}"</strong>?</p>
            <p class="card-text text-muted">Seda toimingut ei saa tagasi pöörata.</p>
            <form method="post">
                {% csrf_token %}
                <div class="d-flex">
                    <button type="submit" class="btn btn-danger me-2">Kustuta</button>
                    <a href="{% url 'superheroes' %}" class="btn btn-secondary">Tühista</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock body %}

superheroes/templates/superheroes/superhero_detail.html
{%extends 'base.html'%}

{% block title %}{{hero.name}}{% endblock title %}

{% block body %}








<section class="bg-white dark:bg-gray-900">
    <div class="gap-16 items-center py-8 px-4 mx-auto max-w-screen-xl lg:grid lg:grid-cols-2 lg:py-16 lg:px-6">
        <div class="font-light text-gray-500 sm:text-lg dark:text-gray-400">
            <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">{{hero.name}}</h2>
            <ul>
                <li><b>Kodanikunimi:</b> {{hero.civillian_name}}</li>
                <li><b>Vanus:</b> {{hero.age}}</li>
                <li><b>Asukoht:</b> {{hero.location}}</li>

            </ul>
            <p class="mb-4">{{hero.description|linebreaks}}</p>
            
        </div>
        <div class="grid ">
            <img class="w-full rounded-lg" src="{{hero.image.url}}" alt="{{hero.name}}">
            
        </div>
    </div>
</section>





            


{% endblock body %}

superheroes/templates/superheroes/superhero_form.html
{%extends 'base.html'%}



{% block title %}{{hero.name}}{% endblock title %}

{% block body %}


<div class="min-h-screen bg-gray-900 flex items-center justify-center">
    <form method="post" enctype="multipart/form-data" class="w-full max-w-lg bg-gray-800 p-8 rounded-lg shadow-md dark:bg-gray-900">
      {% csrf_token %}
  
      <!-- Nimi -->
      <div class="mb-5">
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-100 dark:text-gray-300">Nimi</label>
        <input type="text" name="name" id="id_name" value="{{ hero.name }}" class="shadow-sm bg-gray-700 border border-gray-600 text-gray-100 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-500 dark:text-gray-100 dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light">
      </div>
  
      <!-- Kodanikunimi -->
      <div class="mb-5">
        <label for="id_civillian_name" class="block mb-2 text-sm font-medium text-gray-100 dark:text-gray-300">Kodanikunimi</label>
        <input type="text" name="civillian_name" id="id_civillian_name" value="{{ hero.civillian_name }}" class="shadow-sm bg-gray-700 border border-gray-600 text-gray-100 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-500 dark:text-gray-100 dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light">
      </div>
  
      <!-- Vanus -->
      <div class="mb-5">
        <label for="id_age" class="block mb-2 text-sm font-medium text-gray-100 dark:text-gray-300">Vanus</label>
        <input type="number" name="age" id="id_age" value="{{ hero.age }}" class="shadow-sm bg-gray-700 border border-gray-600 text-gray-100 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-500 dark:text-gray-100 dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light">
      </div>
  
      <!-- Asukoht -->
      <div class="mb-5">
        <label for="id_location" class="block mb-2 text-sm font-medium text-gray-100 dark:text-gray-300">Asukoht</label>
        <input type="text" name="location" id="id_location" value="{{ hero.location }}" class="shadow-sm bg-gray-700 border border-gray-600 text-gray-100 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-500 dark:text-gray-100 dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light">
      </div>
  
      <!-- Kirjeldus -->
      <div class="mb-5">
        <label for="id_description" class="block mb-2 text-sm font-medium text-gray-100 dark:text-gray-300">Kirjeldus</label>
        <textarea name="description" id="id_description" rows="5" class="shadow-sm bg-gray-700 border border-gray-600 text-gray-100 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-500 dark:text-gray-100 dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light">{{ hero.description }}</textarea>
      </div>
      
  
      <!-- Pildi üleslaadimise väli -->
      <div class="mb-5">
        <label for="id_image" class="block mb-2 text-sm font-medium text-gray-100 dark:text-gray-300">Pilt</label>
        <input type="file" name="image" id="id_image" class="shadow-sm bg-gray-700 border border-gray-600 text-gray-100 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-500 dark:text-gray-100 dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light">
        {% if hero.image %}
        <p class="text-sm font-medium text-gray-100 dark:text-gray-300 mt-1">Hetkel: {{ hero.image.url }}</p>
        {% endif %}
      </div>
  
      <!-- Nupp -->
      <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Salvesta
      </button>
    </form>
  </div>
{% endblock body %}

superheroes/templates/superheroes/superheroes.html
{%extends 'base.html'%}

{% block title %}Superkangelased{% endblock title %}
{% block css_files %}
{% endblock css_files %}

{% block body %}


<div class="relative overflow-x-auto shadow-md">
  <div class="flex items-center justify-between p-5 bg-white dark:bg-gray-800">
    <div>
      <h1 class="text-lg font-semibold text-gray-900 dark:text-white">Meie kangelased</h1>
      <p class="mt-1 text-sm font-normal text-gray-500 dark:text-gray-400">Maa viimane kaitse kurjuse jõudude vastu.</p>
    </div>
    <a href="{%url 'superhero_create'%}" class="relative inline-flex items-center justify-center p-0.5 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-500 to-pink-500 group-hover:from-purple-500 group-hover:to-pink-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-purple-200 dark:focus:ring-purple-800">
      <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
        Lisa kangelane
      </span>
    </a>
  </div>
  <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
        <th scope="col" class="px-6 py-3">Nr</th>
        <th scope="col" class="px-6 py-3">Nimi</th>
        <th scope="col" class="px-6 py-3">Kodanikunimi</th>
        <th scope="col" class="px-6 py-3">Asukoht</th>
        <th scope="col" class="px-6 py-3">Valikud</th>
      </tr>
    </thead>
    <tbody>
      {% for hero in superheroes %}
      <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
        <td class="px-6 py-4">{{ forloop.counter }}</td>
        <td class="px-6 py-4">{{ hero.name }}</td>
        <td class="px-6 py-4">{{ hero.civillian_name }}</td>
        <td class="px-6 py-4">{{ hero.location }}</td>
        <td class="px-6 py-4">
          <a href="{{ hero.id }}" class="relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-500 to-pink-500 group-hover:from-purple-500 group-hover:to-pink-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-purple-200 dark:focus:ring-purple-800">
            <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
              Detailid
            </span>
          </a>
          <a href="{{ hero.id }}/update/" class="relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-500 to-pink-500 group-hover:from-purple-500 group-hover:to-pink-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-purple-200 dark:focus:ring-purple-800">
            <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
              Muuda
            </span>
          </a>
          <a href="{{ hero.id }}/delete/" class="relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-500 to-pink-500 group-hover:from-purple-500 group-hover:to-pink-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-purple-200 dark:focus:ring-purple-800">
            <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
              Kustuta
            </span>
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock body %}

weather/templates/weather/result.html
{%extends 'base.html'%}

{% block title %}Ilm{% endblock title %}


{% block body %}

<div class="container my-5">
    <h1 class="text-center">{{ weather.city }}</h1>
    {% if weather.error %}
        <p class="text-danger text-center">{{ weather.error }}</p>
    {% else %}
        <p class="text-center">Temperatuur: <strong>{{ weather.temperature }}°C</strong></p>
        <p class="text-center">Tundub nagu: <em>{{ weather.feels_like }}°C</em></p>
        <p class="text-center">Tuulekiirus: <em>{{ weather.wind_speed}}m/s</em></p>
        <p class="text-center">Tuulesuund: <em>{{ weather.wind_direction }}°</em></p>
        <div class="text-center">
            <img src="http://openweathermap.org/img/wn/{{ weather.icon }}@2x.png" alt="Weather icon">
        </div>
    {% endif %}
    <div class="text-center mt-4">
        <a href="{% url 'weather_search' %}" class="btn btn-secondary">Tagasi</a>
    </div>
</div>
{% endblock body %}

weather/templates/weather/weather.html
{%extends 'base.html'%}


{% block title %} Ilm {% endblock title %}

{% block body %}

<div class="container my-5">
    <h1 class="text-center mb-4">Ilmavõlur</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Otsi</button>
    </form>
</div>

{% endblock body %}